name: Build Super AWS S3 and S3 compatible storage command line tool

on:
   push:
     branches:
       - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.22]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -o s9cmd
    - name: Archive artifact
      run: zip -r s9cmd_${{ matrix.os }}.zip s9cmd
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: s9cmd_${{ matrix.os }}.zip
        path: s9cmd_${{ matrix.os }}.zip
